# Generated by Django 5.0.3 on 2025-04-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_type',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
