# Generated by Django 5.2 on 2025-05-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_year1_sem1_student_year1_sem2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_semester',
            field=models.CharField(blank=True, choices=[('A', 'Semester A'), ('B', 'Semester B')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='current_year_of_study',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
