# Generated by Django 5.0.3 on 2025-04-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_request_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('other', 'Other'), ('iron_swords', 'Alternative Assignment for Iron Swords'), ('delay_submission', 'Assignment Submission Extension'), ('course_unblock', 'Course Unblocking'), ('cancel_hw_percent', 'Cancel Homework Percentage in Final Grade'), ('prerequisite_exemption', 'Prerequisite Exemption'), ('increase_credits', 'Credit Limit Increase'), ('registration_exemption', 'Exemption from Course Registration'), ('special_exam', 'Special Exam Request'), ('course_exemption', 'Course Exemption Request'), ('military_docs', 'Reserve Duty Documentation'), ('include_hw_grade', 'Include Homework in Final Grade')], default='other', max_length=50),
        ),
    ]
