# Generated by Django 5.2 on 2025-05-05 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_id_number_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='שם הקורס')),
                ('semester', models.CharField(choices=[('A', 'סמסטר א'), ('B', 'סמסטר ב')], max_length=1, null=True, verbose_name='סמסטר לימוד הקורס')),
                ('year_of_study', models.IntegerField(choices=[(1, 'שנה א'), (2, 'שנה ב'), (3, 'שנה ג'), (4, 'שנה ד')], null=True, verbose_name='שנת לימוד הקורס')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, help_text='פורמט: 2022-2023', max_length=9, null=True, verbose_name='שנה אקדמית')),
                ('semester', models.CharField(choices=[('A', 'סמסטר א'), ('B', 'סמסטר ב')], max_length=1, verbose_name='סמסטר')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'academic_year', 'semester')},
            },
        ),
    ]
