# Generated by Django 5.0.3 on 2025-05-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_id_number_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('other', 'אחר'), ('cancel_hw_percent', 'ביטול % אחוז עבודות בית בציון הסופי'), ('special_exam', 'בקשה למועד מיוחד'), ('iron_swords', 'בקשה למטלה חלופית - חרבות ברזל'), ('prerequisite_exemption', 'בקשה לפטור מדרישות קדם'), ('course_exemption', 'בקשה לפטור מקורס'), ('delay_submission', 'דחיית הגשת עבודה'), ('increase_credits', 'הגדלת נ"ז מעבר למותר'), ('military_docs', 'הגשת אישורי מילואים'), ('course_unblock', 'שחרור חסימת קורס'), ('registration_exemption', 'שחרור מחובת הרשמה'), ('include_hw_grade', 'שקלול עבודות בית בציון הסופי')], default='other', max_length=50),
        ),
    ]
