# Generated by Django 5.2 on 2025-05-05 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_course_studentcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, help_text='פורמט: 2022-2023', max_length=9, null=True, verbose_name='שנה אקדמית')),
                ('semester', models.CharField(choices=[('A', 'סמסטר א'), ('B', 'סמסטר ב')], max_length=1, verbose_name='סמסטר')),
                ('academic_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.academicstaff')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
            options={
                'verbose_name': 'שיוך קורס למרצה',
                'verbose_name_plural': 'שיוכי קורסים למרצים',
                'unique_together': {('course', 'academic_staff', 'academic_year', 'semester')},
            },
        ),
    ]
